import { CardRarity } from './rarity'
import { JARDIM_SECRETO_IMAGES } from '../assets/cards/jardim-secreto'
import { DEXTER_IMAGES } from '../assets/cards/dexter'
import { LUCIFER_IMAGES } from '../assets/cards/lucifer-fallen-angel'
import { LOL_IMAGES } from '../assets/cards/league-of-legends'

export interface CardDefinition {
  id: string
  name: string
  rarity: CardRarity
  collectionId: string
  number: number
  image: string
  secret?: boolean // carta bônus, não entra na numeração oficial da coleção — mas sorteia normal
}

export const COLLECTIONS = {
  'jardim-secreto': {
    id: 'jardim-secreto',
    name: 'Jardim Secreto',
    total: 20,
  },
  'dexter-serie': {
    id: 'dexter-serie',
    name: 'Dexter: Dark Passenger',
    total: 20,
  },
  'lucifer-fallen-angel': {
    id: 'lucifer-fallen-angel',
    name: 'Lúcifer: Fallen Angel',
    total: 20,
  },
  'league-of-legends': {
    id: 'league-of-legends',
    name: 'League of Legends',
    total: 40,
  },
}

export const CARDS: CardDefinition[] = [
  {
    id: 'cogumelo-vermelho',
    name: 'Cogumelo Vermelho',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 1,
    image: JARDIM_SECRETO_IMAGES['cogumelo-vermelho'],
  },
  {
    id: 'folhinha-verde',
    name: 'Folhinha Verde',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 2,
    image: JARDIM_SECRETO_IMAGES['folhinha-verde'],
  },
  {
    id: 'margarida',
    name: 'Margarida',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 3,
    image: JARDIM_SECRETO_IMAGES['margarida'],
  },
  {
    id: 'caracol-jardim',
    name: 'Caracol de Jardim',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 4,
    image: JARDIM_SECRETO_IMAGES['caracol-jardim'],
  },
  {
    id: 'regador-velhinho',
    name: 'Regador Velhinho',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 5,
    image: JARDIM_SECRETO_IMAGES['regador-velhinho'],
  },
  {
    id: 'borboleta-branca',
    name: 'Borboleta Branca',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 6,
    image: JARDIM_SECRETO_IMAGES['borboleta-branca'],
  },
  {
    id: 'xicara-cha',
    name: 'Xícara de Chá Fumegante',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 7,
    image: JARDIM_SECRETO_IMAGES['xicara-cha'],
  },
  {
    id: 'cesta-piquenique',
    name: 'Cesta de Piquenique',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 8,
    image: JARDIM_SECRETO_IMAGES['cesta-piquenique'],
  },
  {
    id: 'cogumelo-azul',
    name: 'Cogumelo Azul Brilhante',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 9,
    image: JARDIM_SECRETO_IMAGES['cogumelo-azul'],
  },
  {
    id: 'coruja-bebe',
    name: 'Coruja Bebê',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 10,
    image: JARDIM_SECRETO_IMAGES['coruja-bebe'],
  },
  {
    id: 'ninho-ovinhos',
    name: 'Ninho com Ovinhos',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 11,
    image: JARDIM_SECRETO_IMAGES['ninho-ovinhos'],
  },
  {
    id: 'lanterna-vagalume',
    name: 'Lanterna de Vagalume',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 12,
    image: JARDIM_SECRETO_IMAGES['lanterna-vagalume'],
  },
  {
    id: 'casinha-arvore',
    name: 'Casinha na Árvore',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 13,
    image: JARDIM_SECRETO_IMAGES['casinha-arvore'],
  },
  {
    id: 'guarda-chuva-folha',
    name: 'Guarda-chuva de Folha',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 14,
    image: JARDIM_SECRETO_IMAGES['guarda-chuva-folha'],
  },
  {
    id: 'raposa-flores',
    name: 'Raposa das Flores',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 15,
    image: JARDIM_SECRETO_IMAGES['raposa-flores'],
  },
  {
    id: 'fada-jardim',
    name: 'Fada do Jardim',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 16,
    image: JARDIM_SECRETO_IMAGES['fada-jardim'],
  },
  {
    id: 'coelho-chapeuzinho',
    name: 'Coelho de Chapéuzinho',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 17,
    image: JARDIM_SECRETO_IMAGES['coelho-chapeuzinho'],
  },
  {
    id: 'filhote-cervo',
    name: 'Filhote de Cervo com Chifres de Flor',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 18,
    image: JARDIM_SECRETO_IMAGES['filhote-cervo'],
  },
  {
    id: 'guardiao-floresta',
    name: 'Guardião da Floresta',
    rarity: 'epica',
    collectionId: 'jardim-secreto',
    number: 19,
    image: JARDIM_SECRETO_IMAGES['guardiao-floresta'],
  },
  {
    id: 'jardim-secreto-lua',
    name: 'Jardim Secreto sob a Lua',
    rarity: 'epica',
    collectionId: 'jardim-secreto',
    number: 20,
    image: JARDIM_SECRETO_IMAGES['jardim-secreto-lua'],
  },

  // ─── Dexter: Dark Passenger ───
  {
    id: 'blood-slide',
    name: 'Blood Slide',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 1,
    image: DEXTER_IMAGES['blood-slide'],
  },
  {
    id: 'luvas-de-latex',
    name: 'Luvas de Látex',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 2,
    image: DEXTER_IMAGES['luvas-de-latex'],
  },
  {
    id: 'harry-morgan',
    name: 'Harry Morgan',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 3,
    image: DEXTER_IMAGES['harry-morgan'],
  },
  {
    id: 'seringa-m99',
    name: 'Seringa M99',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 4,
    image: DEXTER_IMAGES['seringa-m99'],
  },
  {
    id: 'brian-moser',
    name: 'Brian Moser',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 5,
    image: DEXTER_IMAGES['brian-moser'],
  },
  {
    id: 'donuts',
    name: 'Donuts',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 6,
    image: DEXTER_IMAGES['donuts'],
  },
  {
    id: 'miguel-prado',
    name: 'Miguel Prado',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 7,
    image: DEXTER_IMAGES['miguel-prado'],
  },
  {
    id: 'gota-de-sangue',
    name: 'Gota de Sangue',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 8,
    image: DEXTER_IMAGES['gota-de-sangue'],
  },
  {
    id: 'unhas-coloridas',
    name: 'Unhas Coloridas',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 9,
    image: DEXTER_IMAGES['unhas-coloridas'],
  },
  {
    id: 'trinity-killer',
    name: 'Trinity Killer',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 10,
    image: DEXTER_IMAGES['trinity-killer'],
  },
  {
    id: 'slice-of-life',
    name: 'Slice of Life',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 11,
    image: DEXTER_IMAGES['slice-of-life'],
  },
  {
    id: 'kill-room',
    name: 'Kill Room',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 12,
    image: DEXTER_IMAGES['kill-room'],
  },
  {
    id: 'colecao-de-blood-slides',
    name: 'Coleção de Blood Slides',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 13,
    image: DEXTER_IMAGES['colecao-de-blood-slides'],
  },
  {
    id: 'nascidos-em-sangue',
    name: 'Nascidos em Sangue',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 14,
    image: DEXTER_IMAGES['nascidos-em-sangue'],
  },
  {
    id: 'dexter-morgan',
    name: 'Dexter Morgan',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 15,
    image: DEXTER_IMAGES['dexter-morgan'],
  },
  {
    id: 'rita-morgan',
    name: 'Rita Morgan',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 16,
    image: DEXTER_IMAGES['rita-morgan'],
  },
  {
    id: 'debra-morgan',
    name: 'Debra Morgan',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 17,
    image: DEXTER_IMAGES['debra-morgan'],
  },
  {
    id: 'lila-west',
    name: 'Lila West',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 18,
    image: DEXTER_IMAGES['lila-west'],
  },
  {
    id: 'codigo-de-harry',
    name: 'Código de Harry',
    rarity: 'epica',
    collectionId: 'dexter-serie',
    number: 19,
    image: DEXTER_IMAGES['codigo-de-harry'],
  },
  {
    id: 'banho-de-sangue',
    name: 'Banho de Sangue',
    rarity: 'epica',
    collectionId: 'dexter-serie',
    number: 20,
    image: DEXTER_IMAGES['banho-de-sangue'],
  },
  {
    id: 'sargento-doakes',
    name: 'Sargento Doakes',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 21,
    image: DEXTER_IMAGES['sargento-doakes'],
    secret: true,
  },
  // ─── Lúcifer: Fallen Angel ───
  {
    id: 'taca-de-uisque',
    name: 'Taça de Uísque',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 1,
    image: LUCIFER_IMAGES['taca-de-uisque'],
  },
  {
    id: 'piano',
    name: 'Piano',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 2,
    image: LUCIFER_IMAGES['piano'],
  },
  {
    id: 'pentagrama',
    name: 'Pentagrama',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 3,
    image: LUCIFER_IMAGES['pentagrama'],
  },
  {
    id: 'chave-do-inferno',
    name: 'Chave do Inferno',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 4,
    image: LUCIFER_IMAGES['chave-do-inferno'],
  },
  {
    id: 'distintivo-da-policia',
    name: 'Distintivo da Polícia',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 5,
    image: LUCIFER_IMAGES['distintivo-da-policia'],
  },
  {
    id: 'chave-do-ceu',
    name: 'Chave do Céu',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 6,
    image: LUCIFER_IMAGES['chave-do-ceu'],
  },
  {
    id: 'biblia',
    name: 'Bíblia',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 7,
    image: LUCIFER_IMAGES['biblia'],
  },
  {
    id: 'ceu',
    name: 'Céu',
    rarity: 'comum',
    collectionId: 'lucifer-fallen-angel',
    number: 8,
    image: LUCIFER_IMAGES['ceu'],
  },
  {
    id: 'maze',
    name: 'Maze',
    rarity: 'incomum',
    collectionId: 'lucifer-fallen-angel',
    number: 9,
    image: LUCIFER_IMAGES['maze'],
  },
  {
    id: 'ella-lopez',
    name: 'Ella Lopez',
    rarity: 'incomum',
    collectionId: 'lucifer-fallen-angel',
    number: 10,
    image: LUCIFER_IMAGES['ella-lopez'],
  },
  {
    id: 'dan-espinoza',
    name: 'Dan Espinoza',
    rarity: 'incomum',
    collectionId: 'lucifer-fallen-angel',
    number: 11,
    image: LUCIFER_IMAGES['dan-espinoza'],
  },
  {
    id: 'amenadiel',
    name: 'Amenadiel',
    rarity: 'incomum',
    collectionId: 'lucifer-fallen-angel',
    number: 12,
    image: LUCIFER_IMAGES['amenadiel'],
  },
  {
    id: 'dr-linda-martin',
    name: 'Dr. Linda Martin',
    rarity: 'incomum',
    collectionId: 'lucifer-fallen-angel',
    number: 13,
    image: LUCIFER_IMAGES['dr-linda-martin'],
  },
  {
    id: 'coroa-do-inferno',
    name: 'Coroa do Inferno',
    rarity: 'incomum',
    collectionId: 'lucifer-fallen-angel',
    number: 14,
    image: LUCIFER_IMAGES['coroa-do-inferno'],
  },
  {
    id: 'lucifer-morningstar',
    name: 'Lúcifer Morningstar',
    rarity: 'rara',
    collectionId: 'lucifer-fallen-angel',
    number: 15,
    image: LUCIFER_IMAGES['lucifer-morningstar'],
  },
  {
    id: 'chloe-decker',
    name: 'Chloe Decker',
    rarity: 'rara',
    collectionId: 'lucifer-fallen-angel',
    number: 16,
    image: LUCIFER_IMAGES['chloe-decker'],
  },
  {
    id: 'espada-de-azrael',
    name: 'Espada de Azrael',
    rarity: 'rara',
    collectionId: 'lucifer-fallen-angel',
    number: 17,
    image: LUCIFER_IMAGES['espada-de-azrael'],
  },
  {
    id: 'moeda-de-caronte',
    name: 'Moeda de Caronte',
    rarity: 'rara',
    collectionId: 'lucifer-fallen-angel',
    number: 18,
    image: LUCIFER_IMAGES['moeda-de-caronte'],
  },
  {
    id: 'lucifer-e-chloe',
    name: 'Lúcifer e Chloe',
    rarity: 'epica',
    collectionId: 'lucifer-fallen-angel',
    number: 19,
    image: LUCIFER_IMAGES['lucifer-e-chloe'],
  },
  {
    id: 'asas-de-lucifer',
    name: 'Asas de Lúcifer',
    rarity: 'epica',
    collectionId: 'lucifer-fallen-angel',
    number: 20,
    image: LUCIFER_IMAGES['asas-de-lucifer'],
  },
  // ─── League of Legends ───
  {
    id: 'thresh',
    name: 'Thresh',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 1,
    image: LOL_IMAGES['thresh'],
  },
  {
    id: 'yasuo',
    name: 'Yasuo',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 2,
    image: LOL_IMAGES['yasuo'],
  },
  {
    id: 'zed',
    name: 'Zed',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 3,
    image: LOL_IMAGES['zed'],
  },
  {
    id: 'vi',
    name: 'Vi',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 4,
    image: LOL_IMAGES['vi'],
  },
  {
    id: 'ekko',
    name: 'Ekko',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 5,
    image: LOL_IMAGES['ekko'],
  },
  {
    id: 'katarina',
    name: 'Katarina',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 6,
    image: LOL_IMAGES['katarina'],
  },
  {
    id: 'twitch',
    name: 'Twitch',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 7,
    image: LOL_IMAGES['twitch'],
  },
  {
    id: 'vex',
    name: 'Vex',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 8,
    image: LOL_IMAGES['vex'],
  },
  {
    id: 'zyra',
    name: 'Zyra',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 9,
    image: LOL_IMAGES['zyra'],
  },
  {
    id: 'kha-zix',
    name: "Kha'Zix",
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 10,
    image: LOL_IMAGES['kha-zix'],
  },
  {
    id: 'anivia',
    name: 'Anivia',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 11,
    image: LOL_IMAGES['anivia'],
  },
  {
    id: 'bardo',
    name: 'Bardo',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 12,
    image: LOL_IMAGES['bardo'],
  },
  {
    id: 'alistar',
    name: 'Alistar',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 13,
    image: LOL_IMAGES['alistar'],
  },
  {
    id: 'rammus',
    name: 'Rammus',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 14,
    image: LOL_IMAGES['rammus'],
  },
  {
    id: 'zac',
    name: 'Zac',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 15,
    image: LOL_IMAGES['zac'],
  },
  {
    id: 'cassiopeia',
    name: 'Cassiopeia',
    rarity: 'comum',
    collectionId: 'league-of-legends',
    number: 16,
    image: LOL_IMAGES['cassiopeia'],
  },
  {
    id: 'jinx',
    name: 'Jinx',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 17,
    image: LOL_IMAGES['jinx'],
  },
  {
    id: 'irelia',
    name: 'Irelia',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 18,
    image: LOL_IMAGES['irelia'],
  },
  {
    id: 'gwen',
    name: 'Gwen',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 19,
    image: LOL_IMAGES['gwen'],
  },
  {
    id: 'kayn',
    name: 'Kayn',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 20,
    image: LOL_IMAGES['kayn'],
  },
  {
    id: 'syndra',
    name: 'Syndra',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 21,
    image: LOL_IMAGES['syndra'],
  },
  {
    id: 'taliyah',
    name: 'Taliyah',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 22,
    image: LOL_IMAGES['taliyah'],
  },
  {
    id: 'ivern',
    name: 'Ivern',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 23,
    image: LOL_IMAGES['ivern'],
  },
  {
    id: 'lillia',
    name: 'Lillia',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 24,
    image: LOL_IMAGES['lillia'],
  },
  {
    id: 'amumu',
    name: 'Amumu',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 25,
    image: LOL_IMAGES['amumu'],
  },
  {
    id: 'shaco',
    name: 'Shaco',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 26,
    image: LOL_IMAGES['shaco'],
  },
  {
    id: 'singed',
    name: 'Singed',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 27,
    image: LOL_IMAGES['singed'],
  },
  {
    id: 'nunu-e-willump',
    name: 'Nunu & Willump',
    rarity: 'incomum',
    collectionId: 'league-of-legends',
    number: 28,
    image: LOL_IMAGES['nunu-e-willump'],
  },
  {
    id: 'lux',
    name: 'Lux',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 29,
    image: LOL_IMAGES['lux'],
  },
  {
    id: 'sylas',
    name: 'Sylas',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 30,
    image: LOL_IMAGES['sylas'],
  },
  {
    id: 'quinn',
    name: 'Quinn',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 31,
    image: LOL_IMAGES['quinn'],
  },
  {
    id: 'soraka',
    name: 'Soraka',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 32,
    image: LOL_IMAGES['soraka'],
  },
  {
    id: 'malphite',
    name: 'Malphite',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 33,
    image: LOL_IMAGES['malphite'],
  },
  {
    id: 'vladimir',
    name: 'Vladimir',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 34,
    image: LOL_IMAGES['vladimir'],
  },
  {
    id: 'lulu',
    name: 'Lulu',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 35,
    image: LOL_IMAGES['lulu'],
  },
  {
    id: 'milio',
    name: 'Milio',
    rarity: 'rara',
    collectionId: 'league-of-legends',
    number: 36,
    image: LOL_IMAGES['milio'],
  },
  {
    id: 'kassadin',
    name: 'Kassadin',
    rarity: 'epica',
    collectionId: 'league-of-legends',
    number: 37,
    image: LOL_IMAGES['kassadin'],
  },
  {
    id: 'mel',
    name: 'Mel',
    rarity: 'epica',
    collectionId: 'league-of-legends',
    number: 38,
    image: LOL_IMAGES['mel'],
  },
  {
    id: 'yuumi',
    name: 'Yuumi',
    rarity: 'epica',
    collectionId: 'league-of-legends',
    number: 39,
    image: LOL_IMAGES['yuumi'],
  },
  {
    id: 'nami',
    name: 'Nami',
    rarity: 'epica',
    collectionId: 'league-of-legends',
    number: 40,
    image: LOL_IMAGES['nami'],
  },
]
