import { CardRarity } from './rarity'
import { JARDIM_SECRETO_IMAGES } from '../assets/cards/jardim-secreto'
import { DEXTER_IMAGES } from '../assets/cards/dexter'

export interface CardDefinition {
  id: string
  name: string
  rarity: CardRarity
  collectionId: string
  number: number
  image: string
  secret?: boolean // carta bônus, não entra na numeração oficial da coleção — mas sorteia normal
}

export const COLLECTIONS = {
  'jardim-secreto': {
    id: 'jardim-secreto',
    name: 'Jardim Secreto',
    total: 20,
  },
  'dexter-serie': {
    id: 'dexter-serie',
    name: 'Dexter: Dark Passenger',
    total: 20,
  },
}

export const CARDS: CardDefinition[] = [
  {
    id: 'cogumelo-vermelho',
    name: 'Cogumelo Vermelho',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 1,
    image: JARDIM_SECRETO_IMAGES['cogumelo-vermelho'],
  },
  {
    id: 'folhinha-verde',
    name: 'Folhinha Verde',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 2,
    image: JARDIM_SECRETO_IMAGES['folhinha-verde'],
  },
  {
    id: 'margarida',
    name: 'Margarida',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 3,
    image: JARDIM_SECRETO_IMAGES['margarida'],
  },
  {
    id: 'caracol-jardim',
    name: 'Caracol de Jardim',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 4,
    image: JARDIM_SECRETO_IMAGES['caracol-jardim'],
  },
  {
    id: 'regador-velhinho',
    name: 'Regador Velhinho',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 5,
    image: JARDIM_SECRETO_IMAGES['regador-velhinho'],
  },
  {
    id: 'borboleta-branca',
    name: 'Borboleta Branca',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 6,
    image: JARDIM_SECRETO_IMAGES['borboleta-branca'],
  },
  {
    id: 'xicara-cha',
    name: 'Xícara de Chá Fumegante',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 7,
    image: JARDIM_SECRETO_IMAGES['xicara-cha'],
  },
  {
    id: 'cesta-piquenique',
    name: 'Cesta de Piquenique',
    rarity: 'comum',
    collectionId: 'jardim-secreto',
    number: 8,
    image: JARDIM_SECRETO_IMAGES['cesta-piquenique'],
  },
  {
    id: 'cogumelo-azul',
    name: 'Cogumelo Azul Brilhante',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 9,
    image: JARDIM_SECRETO_IMAGES['cogumelo-azul'],
  },
  {
    id: 'coruja-bebe',
    name: 'Coruja Bebê',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 10,
    image: JARDIM_SECRETO_IMAGES['coruja-bebe'],
  },
  {
    id: 'ninho-ovinhos',
    name: 'Ninho com Ovinhos',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 11,
    image: JARDIM_SECRETO_IMAGES['ninho-ovinhos'],
  },
  {
    id: 'lanterna-vagalume',
    name: 'Lanterna de Vagalume',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 12,
    image: JARDIM_SECRETO_IMAGES['lanterna-vagalume'],
  },
  {
    id: 'casinha-arvore',
    name: 'Casinha na Árvore',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 13,
    image: JARDIM_SECRETO_IMAGES['casinha-arvore'],
  },
  {
    id: 'guarda-chuva-folha',
    name: 'Guarda-chuva de Folha',
    rarity: 'incomum',
    collectionId: 'jardim-secreto',
    number: 14,
    image: JARDIM_SECRETO_IMAGES['guarda-chuva-folha'],
  },
  {
    id: 'raposa-flores',
    name: 'Raposa das Flores',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 15,
    image: JARDIM_SECRETO_IMAGES['raposa-flores'],
  },
  {
    id: 'fada-jardim',
    name: 'Fada do Jardim',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 16,
    image: JARDIM_SECRETO_IMAGES['fada-jardim'],
  },
  {
    id: 'coelho-chapeuzinho',
    name: 'Coelho de Chapéuzinho',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 17,
    image: JARDIM_SECRETO_IMAGES['coelho-chapeuzinho'],
  },
  {
    id: 'filhote-cervo',
    name: 'Filhote de Cervo com Chifres de Flor',
    rarity: 'rara',
    collectionId: 'jardim-secreto',
    number: 18,
    image: JARDIM_SECRETO_IMAGES['filhote-cervo'],
  },
  {
    id: 'guardiao-floresta',
    name: 'Guardião da Floresta',
    rarity: 'epica',
    collectionId: 'jardim-secreto',
    number: 19,
    image: JARDIM_SECRETO_IMAGES['guardiao-floresta'],
  },
  {
    id: 'jardim-secreto-lua',
    name: 'Jardim Secreto sob a Lua',
    rarity: 'epica',
    collectionId: 'jardim-secreto',
    number: 20,
    image: JARDIM_SECRETO_IMAGES['jardim-secreto-lua'],
  },

  // ─── Dexter: Dark Passenger ───
  {
    id: 'blood-slide',
    name: 'Blood Slide',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 1,
    image: DEXTER_IMAGES['blood-slide'],
  },
  {
    id: 'luvas-de-latex',
    name: 'Luvas de Látex',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 2,
    image: DEXTER_IMAGES['luvas-de-latex'],
  },
  {
    id: 'harry-morgan',
    name: 'Harry Morgan',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 3,
    image: DEXTER_IMAGES['harry-morgan'],
  },
  {
    id: 'seringa-m99',
    name: 'Seringa M99',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 4,
    image: DEXTER_IMAGES['seringa-m99'],
  },
  {
    id: 'brian-moser',
    name: 'Brian Moser',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 5,
    image: DEXTER_IMAGES['brian-moser'],
  },
  {
    id: 'donuts',
    name: 'Donuts',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 6,
    image: DEXTER_IMAGES['donuts'],
  },
  {
    id: 'miguel-prado',
    name: 'Miguel Prado',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 7,
    image: DEXTER_IMAGES['miguel-prado'],
  },
  {
    id: 'gota-de-sangue',
    name: 'Gota de Sangue',
    rarity: 'comum',
    collectionId: 'dexter-serie',
    number: 8,
    image: DEXTER_IMAGES['gota-de-sangue'],
  },
  {
    id: 'unhas-coloridas',
    name: 'Unhas Coloridas',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 9,
    image: DEXTER_IMAGES['unhas-coloridas'],
  },
  {
    id: 'trinity-killer',
    name: 'Trinity Killer',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 10,
    image: DEXTER_IMAGES['trinity-killer'],
  },
  {
    id: 'slice-of-life',
    name: 'Slice of Life',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 11,
    image: DEXTER_IMAGES['slice-of-life'],
  },
  {
    id: 'kill-room',
    name: 'Kill Room',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 12,
    image: DEXTER_IMAGES['kill-room'],
  },
  {
    id: 'colecao-de-blood-slides',
    name: 'Coleção de Blood Slides',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 13,
    image: DEXTER_IMAGES['colecao-de-blood-slides'],
  },
  {
    id: 'nascidos-em-sangue',
    name: 'Nascidos em Sangue',
    rarity: 'incomum',
    collectionId: 'dexter-serie',
    number: 14,
    image: DEXTER_IMAGES['nascidos-em-sangue'],
  },
  {
    id: 'dexter-morgan',
    name: 'Dexter Morgan',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 15,
    image: DEXTER_IMAGES['dexter-morgan'],
  },
  {
    id: 'rita-morgan',
    name: 'Rita Morgan',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 16,
    image: DEXTER_IMAGES['rita-morgan'],
  },
  {
    id: 'debra-morgan',
    name: 'Debra Morgan',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 17,
    image: DEXTER_IMAGES['debra-morgan'],
  },
  {
    id: 'lila-west',
    name: 'Lila West',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 18,
    image: DEXTER_IMAGES['lila-west'],
  },
  {
    id: 'codigo-de-harry',
    name: 'Código de Harry',
    rarity: 'epica',
    collectionId: 'dexter-serie',
    number: 19,
    image: DEXTER_IMAGES['codigo-de-harry'],
  },
  {
    id: 'banho-de-sangue',
    name: 'Banho de Sangue',
    rarity: 'epica',
    collectionId: 'dexter-serie',
    number: 20,
    image: DEXTER_IMAGES['banho-de-sangue'],
  },
  {
    id: 'sargento-doakes',
    name: 'Sargento Doakes',
    rarity: 'rara',
    collectionId: 'dexter-serie',
    number: 21,
    image: DEXTER_IMAGES['sargento-doakes'],
    secret: true,
  },
]
