export interface StickerItem {
  key: string
  file: string
}

export interface StickerPack {
  id: string
  label: string
  price: number
  preview: string // primeiro sticker do pack pra mostrar como capa
  stickers: StickerItem[]
}

export const STICKER_PACKS: StickerPack[] = [
  {
    id: 'axolot',
    label: 'Axolotl',
    price: 80,
    preview: 'axolot/1.png',
    stickers: Array.from({ length: 21 }, (_, i) => ({
      key: `axolot-${i + 1}`,
      file: `axolot/${i + 1}.png`,
    })),
  },
  {
    id: 'birthday',
    label: 'Aniversário',
    price: 60,
    preview: 'birthday/birthday-cake.png',
    stickers: [
      'badge',
      'balloons',
      'beverage',
      'birthday-cake',
      'boy',
      'cake',
      'candle',
      'candy (1)',
      'candy',
      'cupcake',
      'firework',
      'garland',
      'giftbox',
      'girl',
      'ice-cream',
      'invitation',
      'mic',
      'party-glasses',
      'party-hat',
      'party-whistle',
      'photo-camera',
      'pizza',
      'present',
      'snack',
    ].map((n) => ({ key: `birthday-${n}`, file: `birthday/${n}.png` })),
  },
  {
    id: 'boy',
    label: 'Menino Anime',
    price: 70,
    preview: 'boy/happy.png',
    stickers: [
      'angry',
      'blushing',
      'confused',
      'disbelief',
      'excited',
      'good',
      'happy',
      'hi',
      'love',
      'mocking',
      'no',
      'ok',
      'peace',
      'sad',
      'shocked',
      'shy',
      'sick',
      'sing',
      'yawn',
      'yes',
    ].map((n) => ({ key: `boy-${n}`, file: `boy/${n}.png` })),
  },
  {
    id: 'bw-couple',
    label: 'Casal P&B',
    price: 90,
    preview: 'bw-couple/1.png',
    stickers: Array.from({ length: 20 }, (_, i) => ({
      key: `bw-couple-${i + 1}`,
      file: `bw-couple/${i + 1}.png`,
    })),
  },
  {
    id: 'cats-dogs-birth',
    label: 'Pets Festeiros',
    price: 70,
    preview: 'cats-dogs-birth/cat.png',
    stickers: [
      'black-cat',
      'black-cat1',
      'black-cat2',
      'black-cat3',
      'cat',
      'cat1',
      'cat2',
      'cat3',
      'cat4',
      'cat5',
      'dachshund',
      'dachshund1',
      'dog',
      'dog1',
      'dog2',
      'dog3',
      'dog4',
      'dog5',
      'pug',
      'puppy',
    ].map((n) => ({ key: `cats-${n}`, file: `cats-dogs-birth/${n}.png` })),
  },
  {
    id: 'christmas',
    label: 'Natal',
    price: 60,
    preview: 'christmas/snowman.png',
    stickers: [
      'angry',
      'bell',
      'bell1',
      'bell2',
      'bell3',
      'calm',
      'dynamite',
      'firecracker',
      'fork',
      'gingerbread',
      'gingerbread1',
      'gingerbread2',
      'grin',
      'grin1',
      'laughing',
      'laughing1',
      'laughing2',
      'mocking',
      'sad',
      'smiling',
      'smiling1',
      'snowman',
      'spoon',
      'surprised',
      'whiskey',
    ].map((n) => ({ key: `christmas-${n}`, file: `christmas/${n}.png` })),
  },
  {
    id: 'cute-girl',
    label: 'Menina Fofa',
    price: 70,
    preview: 'cute-girl/proud.png',
    stickers: [
      'angry',
      'bath',
      'bored',
      'cry',
      'eat',
      'eating',
      'hide',
      'peek',
      'pray',
      'proud',
      'reading-book',
      'sleepy',
      'smelly',
      'snuggle',
      'sorry',
      'waiting',
      'watching',
      'whisper',
      'window',
      'writing',
    ].map((n) => ({ key: `cute-girl-${n}`, file: `cute-girl/${n}.png` })),
  },
  {
    id: 'girl',
    label: 'Garota Anime',
    price: 70,
    preview: 'girl/happy.png',
    stickers: [
      'angry',
      'blushing',
      'confused',
      'disbelief',
      'excited',
      'fever',
      'good',
      'happy',
      'hi',
      'love',
      'mockery',
      'no',
      'ok',
      'peace',
      'sad',
      'shocked',
      'shy',
      'sing',
      'yawn',
      'yes',
    ].map((n) => ({ key: `girl-${n}`, file: `girl/${n}.png` })),
  },
  {
    id: 'relax-pack',
    label: 'Relax',
    price: 60,
    preview: 'relax-pack/heart.png',
    stickers: [
      'backpack',
      'book',
      'burger',
      'cake-slice',
      'cheese',
      'clapboard',
      'crown',
      'flower',
      'gramophone',
      'heart',
      'kitten',
      'muffin',
      'pizza',
      'pop-corn',
      'saturn',
      'shooting-star',
      'symbol',
      'tea-pot',
      'ufo',
      'watermelon',
    ].map((n) => ({ key: `relax-${n}`, file: `relax-pack/${n}.png` })),
  },
  {
    id: 'valentines',
    label: 'Valentines',
    price: 80,
    preview: 'valentines/love.png',
    stickers: [
      'bee',
      'be-mine',
      'cassette-tape',
      'chocolate-box',
      'coffee-cup',
      'cookies',
      'cupid',
      'got-you',
      'i-love-you',
      'i-love-you1',
      'love',
      'love1',
      'love-birds',
      'love-letter',
      'love-message',
      'love-message1',
      'love-song',
      'stamp',
      'valentines-day',
      'you-have-the-key',
    ].map((n) => ({ key: `valentines-${n}`, file: `valentines/${n}.png` })),
  },
  {
    id: 'valentines-1',
    label: 'Valentines II',
    price: 80,
    preview: 'valentines-1/love.png',
    stickers: [
      'call',
      'cat',
      'chocolate-box',
      'chocolate-box1',
      'dog',
      'drink',
      'heart',
      'in-love',
      'letter',
      'lock',
      'love',
      'love-potion',
      'man',
      'message',
      'milkshake',
      'postcard',
      'rabbit',
      'rose',
      'stamp',
      'valentine',
    ].map((n) => ({ key: `valentines1-${n}`, file: `valentines-1/${n}.png` })),
  },
]
